/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CodComboAll1Builder {
    //the instance to build
    private CodComboAll1 codComboAll1;

    /**
     * Default constructor to initialize the instance
     */
    public CodComboAll1Builder() {
        codComboAll1 = new CodComboAll1();
    }

    public CodComboAll1Builder id(int id) {
        codComboAll1.setId(id);
        return this;
    }

    public CodComboAll1Builder designacaoDistrito(String designacaoDistrito) {
        codComboAll1.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public CodComboAll1Builder designacaoConcelho(String designacaoConcelho) {
        codComboAll1.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public CodComboAll1Builder codLocalidade(String codLocalidade) {
        codComboAll1.setCodLocalidade(codLocalidade);
        return this;
    }

    public CodComboAll1Builder localidade(String localidade) {
        codComboAll1.setLocalidade(localidade);
        return this;
    }

    public CodComboAll1Builder artCod(String artCod) {
        codComboAll1.setArtCod(artCod);
        return this;
    }

    public CodComboAll1Builder artTipo(String artTipo) {
        codComboAll1.setArtTipo(artTipo);
        return this;
    }

    public CodComboAll1Builder priPrep(String priPrep) {
        codComboAll1.setPriPrep(priPrep);
        return this;
    }

    public CodComboAll1Builder artTitulo(String artTitulo) {
        codComboAll1.setArtTitulo(artTitulo);
        return this;
    }

    public CodComboAll1Builder segPrep(String segPrep) {
        codComboAll1.setSegPrep(segPrep);
        return this;
    }

    public CodComboAll1Builder artDesig(String artDesig) {
        codComboAll1.setArtDesig(artDesig);
        return this;
    }

    public CodComboAll1Builder artLocal(String artLocal) {
        codComboAll1.setArtLocal(artLocal);
        return this;
    }

    public CodComboAll1Builder troco(String troco) {
        codComboAll1.setTroco(troco);
        return this;
    }

    public CodComboAll1Builder porta(String porta) {
        codComboAll1.setPorta(porta);
        return this;
    }

    public CodComboAll1Builder cliente(String cliente) {
        codComboAll1.setCliente(cliente);
        return this;
    }

    public CodComboAll1Builder codPostal4(String codPostal4) {
        codComboAll1.setCodPostal4(codPostal4);
        return this;
    }

    public CodComboAll1Builder codPostal3(String codPostal3) {
        codComboAll1.setCodPostal3(codPostal3);
        return this;
    }

    public CodComboAll1Builder cpAlf(String cpAlf) {
        codComboAll1.setCpAlf(cpAlf);
        return this;
    }

    public CodComboAll1Builder latitude(String latitude) {
        codComboAll1.setLatitude(latitude);
        return this;
    }

    public CodComboAll1Builder longitude(String longitude) {
        codComboAll1.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CodComboAll1 build() {
        return codComboAll1;
    }
}