/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CodigosDistritoBuilder {
    //the instance to build
    private CodigosDistrito codigosDistrito;

    /**
     * Default constructor to initialize the instance
     */
    public CodigosDistritoBuilder() {
        codigosDistrito = new CodigosDistrito();
    }

    public CodigosDistritoBuilder id(int id) {
        codigosDistrito.setId(id);
        return this;
    }

    public CodigosDistritoBuilder designacaoDistrito(String designacaoDistrito) {
        codigosDistrito.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public CodigosDistritoBuilder designacaoConcelho(String designacaoConcelho) {
        codigosDistrito.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public CodigosDistritoBuilder codLocalidade(String codLocalidade) {
        codigosDistrito.setCodLocalidade(codLocalidade);
        return this;
    }

    public CodigosDistritoBuilder localidade(String localidade) {
        codigosDistrito.setLocalidade(localidade);
        return this;
    }

    public CodigosDistritoBuilder artCod(String artCod) {
        codigosDistrito.setArtCod(artCod);
        return this;
    }

    public CodigosDistritoBuilder artTipo(String artTipo) {
        codigosDistrito.setArtTipo(artTipo);
        return this;
    }

    public CodigosDistritoBuilder priPrep(String priPrep) {
        codigosDistrito.setPriPrep(priPrep);
        return this;
    }

    public CodigosDistritoBuilder artTitulo(String artTitulo) {
        codigosDistrito.setArtTitulo(artTitulo);
        return this;
    }

    public CodigosDistritoBuilder segPrep(String segPrep) {
        codigosDistrito.setSegPrep(segPrep);
        return this;
    }

    public CodigosDistritoBuilder artDesig(String artDesig) {
        codigosDistrito.setArtDesig(artDesig);
        return this;
    }

    public CodigosDistritoBuilder artLocal(String artLocal) {
        codigosDistrito.setArtLocal(artLocal);
        return this;
    }

    public CodigosDistritoBuilder troco(String troco) {
        codigosDistrito.setTroco(troco);
        return this;
    }

    public CodigosDistritoBuilder porta(String porta) {
        codigosDistrito.setPorta(porta);
        return this;
    }

    public CodigosDistritoBuilder cliente(String cliente) {
        codigosDistrito.setCliente(cliente);
        return this;
    }

    public CodigosDistritoBuilder codPostal4(String codPostal4) {
        codigosDistrito.setCodPostal4(codPostal4);
        return this;
    }

    public CodigosDistritoBuilder codPostal3(String codPostal3) {
        codigosDistrito.setCodPostal3(codPostal3);
        return this;
    }

    public CodigosDistritoBuilder cpAlf(String cpAlf) {
        codigosDistrito.setCpAlf(cpAlf);
        return this;
    }

    public CodigosDistritoBuilder latitude(String latitude) {
        codigosDistrito.setLatitude(latitude);
        return this;
    }

    public CodigosDistritoBuilder longitude(String longitude) {
        codigosDistrito.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CodigosDistrito build() {
        return codigosDistrito;
    }
}