/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CodigosCombinarBuilder {
    //the instance to build
    private CodigosCombinar codigosCombinar;

    /**
     * Default constructor to initialize the instance
     */
    public CodigosCombinarBuilder() {
        codigosCombinar = new CodigosCombinar();
    }

    public CodigosCombinarBuilder id(int id) {
        codigosCombinar.setId(id);
        return this;
    }

    public CodigosCombinarBuilder designacaoDistrito(String designacaoDistrito) {
        codigosCombinar.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public CodigosCombinarBuilder designacaoConcelho(String designacaoConcelho) {
        codigosCombinar.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public CodigosCombinarBuilder codLocalidade(String codLocalidade) {
        codigosCombinar.setCodLocalidade(codLocalidade);
        return this;
    }

    public CodigosCombinarBuilder localidade(String localidade) {
        codigosCombinar.setLocalidade(localidade);
        return this;
    }

    public CodigosCombinarBuilder artCod(String artCod) {
        codigosCombinar.setArtCod(artCod);
        return this;
    }

    public CodigosCombinarBuilder artTipo(String artTipo) {
        codigosCombinar.setArtTipo(artTipo);
        return this;
    }

    public CodigosCombinarBuilder priPrep(String priPrep) {
        codigosCombinar.setPriPrep(priPrep);
        return this;
    }

    public CodigosCombinarBuilder artTitulo(String artTitulo) {
        codigosCombinar.setArtTitulo(artTitulo);
        return this;
    }

    public CodigosCombinarBuilder segPrep(String segPrep) {
        codigosCombinar.setSegPrep(segPrep);
        return this;
    }

    public CodigosCombinarBuilder artDesig(String artDesig) {
        codigosCombinar.setArtDesig(artDesig);
        return this;
    }

    public CodigosCombinarBuilder artLocal(String artLocal) {
        codigosCombinar.setArtLocal(artLocal);
        return this;
    }

    public CodigosCombinarBuilder troco(String troco) {
        codigosCombinar.setTroco(troco);
        return this;
    }

    public CodigosCombinarBuilder porta(String porta) {
        codigosCombinar.setPorta(porta);
        return this;
    }

    public CodigosCombinarBuilder cliente(String cliente) {
        codigosCombinar.setCliente(cliente);
        return this;
    }

    public CodigosCombinarBuilder codPostal4(String codPostal4) {
        codigosCombinar.setCodPostal4(codPostal4);
        return this;
    }

    public CodigosCombinarBuilder codPostal3(String codPostal3) {
        codigosCombinar.setCodPostal3(codPostal3);
        return this;
    }

    public CodigosCombinarBuilder cpAlf(String cpAlf) {
        codigosCombinar.setCpAlf(cpAlf);
        return this;
    }

    public CodigosCombinarBuilder latitude(String latitude) {
        codigosCombinar.setLatitude(latitude);
        return this;
    }

    public CodigosCombinarBuilder longitude(String longitude) {
        codigosCombinar.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CodigosCombinar build() {
        return codigosCombinar;
    }
}