/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CodigosLocalidadeBuilder {
    //the instance to build
    private CodigosLocalidade codigosLocalidade;

    /**
     * Default constructor to initialize the instance
     */
    public CodigosLocalidadeBuilder() {
        codigosLocalidade = new CodigosLocalidade();
    }

    public CodigosLocalidadeBuilder id(int id) {
        codigosLocalidade.setId(id);
        return this;
    }

    public CodigosLocalidadeBuilder designacaoDistrito(String designacaoDistrito) {
        codigosLocalidade.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public CodigosLocalidadeBuilder designacaoConcelho(String designacaoConcelho) {
        codigosLocalidade.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public CodigosLocalidadeBuilder codLocalidade(String codLocalidade) {
        codigosLocalidade.setCodLocalidade(codLocalidade);
        return this;
    }

    public CodigosLocalidadeBuilder localidade(String localidade) {
        codigosLocalidade.setLocalidade(localidade);
        return this;
    }

    public CodigosLocalidadeBuilder artCod(String artCod) {
        codigosLocalidade.setArtCod(artCod);
        return this;
    }

    public CodigosLocalidadeBuilder artTipo(String artTipo) {
        codigosLocalidade.setArtTipo(artTipo);
        return this;
    }

    public CodigosLocalidadeBuilder priPrep(String priPrep) {
        codigosLocalidade.setPriPrep(priPrep);
        return this;
    }

    public CodigosLocalidadeBuilder artTitulo(String artTitulo) {
        codigosLocalidade.setArtTitulo(artTitulo);
        return this;
    }

    public CodigosLocalidadeBuilder segPrep(String segPrep) {
        codigosLocalidade.setSegPrep(segPrep);
        return this;
    }

    public CodigosLocalidadeBuilder artDesig(String artDesig) {
        codigosLocalidade.setArtDesig(artDesig);
        return this;
    }

    public CodigosLocalidadeBuilder artLocal(String artLocal) {
        codigosLocalidade.setArtLocal(artLocal);
        return this;
    }

    public CodigosLocalidadeBuilder troco(String troco) {
        codigosLocalidade.setTroco(troco);
        return this;
    }

    public CodigosLocalidadeBuilder porta(String porta) {
        codigosLocalidade.setPorta(porta);
        return this;
    }

    public CodigosLocalidadeBuilder cliente(String cliente) {
        codigosLocalidade.setCliente(cliente);
        return this;
    }

    public CodigosLocalidadeBuilder codPostal4(String codPostal4) {
        codigosLocalidade.setCodPostal4(codPostal4);
        return this;
    }

    public CodigosLocalidadeBuilder codPostal3(String codPostal3) {
        codigosLocalidade.setCodPostal3(codPostal3);
        return this;
    }

    public CodigosLocalidadeBuilder cpAlf(String cpAlf) {
        codigosLocalidade.setCpAlf(cpAlf);
        return this;
    }

    public CodigosLocalidadeBuilder latitude(String latitude) {
        codigosLocalidade.setLatitude(latitude);
        return this;
    }

    public CodigosLocalidadeBuilder longitude(String longitude) {
        codigosLocalidade.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CodigosLocalidade build() {
        return codigosLocalidade;
    }
}