/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CodigosConcelhoBuilder {
    //the instance to build
    private CodigosConcelho codigosConcelho;

    /**
     * Default constructor to initialize the instance
     */
    public CodigosConcelhoBuilder() {
        codigosConcelho = new CodigosConcelho();
    }

    public CodigosConcelhoBuilder id(int id) {
        codigosConcelho.setId(id);
        return this;
    }

    public CodigosConcelhoBuilder designacaoDistrito(String designacaoDistrito) {
        codigosConcelho.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public CodigosConcelhoBuilder designacaoConcelho(String designacaoConcelho) {
        codigosConcelho.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public CodigosConcelhoBuilder codLocalidade(String codLocalidade) {
        codigosConcelho.setCodLocalidade(codLocalidade);
        return this;
    }

    public CodigosConcelhoBuilder localidade(String localidade) {
        codigosConcelho.setLocalidade(localidade);
        return this;
    }

    public CodigosConcelhoBuilder artCod(String artCod) {
        codigosConcelho.setArtCod(artCod);
        return this;
    }

    public CodigosConcelhoBuilder artTipo(String artTipo) {
        codigosConcelho.setArtTipo(artTipo);
        return this;
    }

    public CodigosConcelhoBuilder priPrep(String priPrep) {
        codigosConcelho.setPriPrep(priPrep);
        return this;
    }

    public CodigosConcelhoBuilder artTitulo(String artTitulo) {
        codigosConcelho.setArtTitulo(artTitulo);
        return this;
    }

    public CodigosConcelhoBuilder segPrep(String segPrep) {
        codigosConcelho.setSegPrep(segPrep);
        return this;
    }

    public CodigosConcelhoBuilder artDesig(String artDesig) {
        codigosConcelho.setArtDesig(artDesig);
        return this;
    }

    public CodigosConcelhoBuilder artLocal(String artLocal) {
        codigosConcelho.setArtLocal(artLocal);
        return this;
    }

    public CodigosConcelhoBuilder troco(String troco) {
        codigosConcelho.setTroco(troco);
        return this;
    }

    public CodigosConcelhoBuilder porta(String porta) {
        codigosConcelho.setPorta(porta);
        return this;
    }

    public CodigosConcelhoBuilder cliente(String cliente) {
        codigosConcelho.setCliente(cliente);
        return this;
    }

    public CodigosConcelhoBuilder codPostal4(String codPostal4) {
        codigosConcelho.setCodPostal4(codPostal4);
        return this;
    }

    public CodigosConcelhoBuilder codPostal3(String codPostal3) {
        codigosConcelho.setCodPostal3(codPostal3);
        return this;
    }

    public CodigosConcelhoBuilder cpAlf(String cpAlf) {
        codigosConcelho.setCpAlf(cpAlf);
        return this;
    }

    public CodigosConcelhoBuilder latitude(String latitude) {
        codigosConcelho.setLatitude(latitude);
        return this;
    }

    public CodigosConcelhoBuilder longitude(String longitude) {
        codigosConcelho.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CodigosConcelho build() {
        return codigosConcelho;
    }
}