/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CodPorRua1Builder {
    //the instance to build
    private CodPorRua1 codPorRua1;

    /**
     * Default constructor to initialize the instance
     */
    public CodPorRua1Builder() {
        codPorRua1 = new CodPorRua1();
    }

    public CodPorRua1Builder id(int id) {
        codPorRua1.setId(id);
        return this;
    }

    public CodPorRua1Builder designacaoDistrito(String designacaoDistrito) {
        codPorRua1.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public CodPorRua1Builder designacaoConcelho(String designacaoConcelho) {
        codPorRua1.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public CodPorRua1Builder codLocalidade(String codLocalidade) {
        codPorRua1.setCodLocalidade(codLocalidade);
        return this;
    }

    public CodPorRua1Builder localidade(String localidade) {
        codPorRua1.setLocalidade(localidade);
        return this;
    }

    public CodPorRua1Builder artCod(String artCod) {
        codPorRua1.setArtCod(artCod);
        return this;
    }

    public CodPorRua1Builder artTipo(String artTipo) {
        codPorRua1.setArtTipo(artTipo);
        return this;
    }

    public CodPorRua1Builder priPrep(String priPrep) {
        codPorRua1.setPriPrep(priPrep);
        return this;
    }

    public CodPorRua1Builder artTitulo(String artTitulo) {
        codPorRua1.setArtTitulo(artTitulo);
        return this;
    }

    public CodPorRua1Builder segPrep(String segPrep) {
        codPorRua1.setSegPrep(segPrep);
        return this;
    }

    public CodPorRua1Builder artDesig(String artDesig) {
        codPorRua1.setArtDesig(artDesig);
        return this;
    }

    public CodPorRua1Builder artLocal(String artLocal) {
        codPorRua1.setArtLocal(artLocal);
        return this;
    }

    public CodPorRua1Builder troco(String troco) {
        codPorRua1.setTroco(troco);
        return this;
    }

    public CodPorRua1Builder porta(String porta) {
        codPorRua1.setPorta(porta);
        return this;
    }

    public CodPorRua1Builder cliente(String cliente) {
        codPorRua1.setCliente(cliente);
        return this;
    }

    public CodPorRua1Builder codPostal4(String codPostal4) {
        codPorRua1.setCodPostal4(codPostal4);
        return this;
    }

    public CodPorRua1Builder codPostal3(String codPostal3) {
        codPorRua1.setCodPostal3(codPostal3);
        return this;
    }

    public CodPorRua1Builder cpAlf(String cpAlf) {
        codPorRua1.setCpAlf(cpAlf);
        return this;
    }

    public CodPorRua1Builder latitude(String latitude) {
        codPorRua1.setLatitude(latitude);
        return this;
    }

    public CodPorRua1Builder longitude(String longitude) {
        codPorRua1.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CodPorRua1 build() {
        return codPorRua1;
    }
}