/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class CombinarBuilder {
    //the instance to build
    private Combinar combinar;

    /**
     * Default constructor to initialize the instance
     */
    public CombinarBuilder() {
        combinar = new Combinar();
    }

    public CombinarBuilder id(int id) {
        combinar.setId(id);
        return this;
    }

    public CombinarBuilder designacaoDistrito(String designacaoDistrito) {
        combinar.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public CombinarBuilder designacaoConcelho(String designacaoConcelho) {
        combinar.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public CombinarBuilder codLocalidade(String codLocalidade) {
        combinar.setCodLocalidade(codLocalidade);
        return this;
    }

    public CombinarBuilder localidade(String localidade) {
        combinar.setLocalidade(localidade);
        return this;
    }

    public CombinarBuilder artCod(String artCod) {
        combinar.setArtCod(artCod);
        return this;
    }

    public CombinarBuilder artTipo(String artTipo) {
        combinar.setArtTipo(artTipo);
        return this;
    }

    public CombinarBuilder priPrep(String priPrep) {
        combinar.setPriPrep(priPrep);
        return this;
    }

    public CombinarBuilder artTitulo(String artTitulo) {
        combinar.setArtTitulo(artTitulo);
        return this;
    }

    public CombinarBuilder segPrep(String segPrep) {
        combinar.setSegPrep(segPrep);
        return this;
    }

    public CombinarBuilder artDesig(String artDesig) {
        combinar.setArtDesig(artDesig);
        return this;
    }

    public CombinarBuilder artLocal(String artLocal) {
        combinar.setArtLocal(artLocal);
        return this;
    }

    public CombinarBuilder troco(String troco) {
        combinar.setTroco(troco);
        return this;
    }

    public CombinarBuilder porta(String porta) {
        combinar.setPorta(porta);
        return this;
    }

    public CombinarBuilder cliente(String cliente) {
        combinar.setCliente(cliente);
        return this;
    }

    public CombinarBuilder codPostal4(String codPostal4) {
        combinar.setCodPostal4(codPostal4);
        return this;
    }

    public CombinarBuilder codPostal3(String codPostal3) {
        combinar.setCodPostal3(codPostal3);
        return this;
    }

    public CombinarBuilder cpAlf(String cpAlf) {
        combinar.setCpAlf(cpAlf);
        return this;
    }

    public CombinarBuilder latitude(String latitude) {
        combinar.setLatitude(latitude);
        return this;
    }

    public CombinarBuilder longitude(String longitude) {
        combinar.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Combinar build() {
        return combinar;
    }
}