/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ConNumDist1Builder {
    //the instance to build
    private ConNumDist1 conNumDist1;

    /**
     * Default constructor to initialize the instance
     */
    public ConNumDist1Builder() {
        conNumDist1 = new ConNumDist1();
    }

    public ConNumDist1Builder designacaoDistrito(String designacaoDistrito) {
        conNumDist1.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public ConNumDist1Builder designacaoConcelho(String designacaoConcelho) {
        conNumDist1.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ConNumDist1 build() {
        return conNumDist1;
    }
}