/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ConTodos1Builder {
    //the instance to build
    private ConTodos1 conTodos1;

    /**
     * Default constructor to initialize the instance
     */
    public ConTodos1Builder() {
        conTodos1 = new ConTodos1();
    }

    public ConTodos1Builder designacaoDistrito(String designacaoDistrito) {
        conTodos1.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public ConTodos1Builder designacaoConcelho(String designacaoConcelho) {
        conTodos1.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ConTodos1 build() {
        return conTodos1;
    }
}