/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ConUmConcelho1Builder {
    //the instance to build
    private ConUmConcelho1 conUmConcelho1;

    /**
     * Default constructor to initialize the instance
     */
    public ConUmConcelho1Builder() {
        conUmConcelho1 = new ConUmConcelho1();
    }

    public ConUmConcelho1Builder designacaoDistrito(String designacaoDistrito) {
        conUmConcelho1.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public ConUmConcelho1Builder designacaoConcelho(String designacaoConcelho) {
        conUmConcelho1.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ConUmConcelho1 build() {
        return conUmConcelho1;
    }
}