/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class DistTodos1Builder {
    //the instance to build
    private DistTodos1 distTodos1;

    /**
     * Default constructor to initialize the instance
     */
    public DistTodos1Builder() {
        distTodos1 = new DistTodos1();
    }

    public DistTodos1Builder id(int id) {
        distTodos1.setId(id);
        return this;
    }

    public DistTodos1Builder designacaoDistrito(String designacaoDistrito) {
        distTodos1.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public DistTodos1Builder designacaoConcelho(String designacaoConcelho) {
        distTodos1.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public DistTodos1Builder codLocalidade(String codLocalidade) {
        distTodos1.setCodLocalidade(codLocalidade);
        return this;
    }

    public DistTodos1Builder localidade(String localidade) {
        distTodos1.setLocalidade(localidade);
        return this;
    }

    public DistTodos1Builder artCod(String artCod) {
        distTodos1.setArtCod(artCod);
        return this;
    }

    public DistTodos1Builder artTipo(String artTipo) {
        distTodos1.setArtTipo(artTipo);
        return this;
    }

    public DistTodos1Builder priPrep(String priPrep) {
        distTodos1.setPriPrep(priPrep);
        return this;
    }

    public DistTodos1Builder artTitulo(String artTitulo) {
        distTodos1.setArtTitulo(artTitulo);
        return this;
    }

    public DistTodos1Builder segPrep(String segPrep) {
        distTodos1.setSegPrep(segPrep);
        return this;
    }

    public DistTodos1Builder artDesig(String artDesig) {
        distTodos1.setArtDesig(artDesig);
        return this;
    }

    public DistTodos1Builder artLocal(String artLocal) {
        distTodos1.setArtLocal(artLocal);
        return this;
    }

    public DistTodos1Builder troco(String troco) {
        distTodos1.setTroco(troco);
        return this;
    }

    public DistTodos1Builder porta(String porta) {
        distTodos1.setPorta(porta);
        return this;
    }

    public DistTodos1Builder cliente(String cliente) {
        distTodos1.setCliente(cliente);
        return this;
    }

    public DistTodos1Builder codPostal4(String codPostal4) {
        distTodos1.setCodPostal4(codPostal4);
        return this;
    }

    public DistTodos1Builder codPostal3(String codPostal3) {
        distTodos1.setCodPostal3(codPostal3);
        return this;
    }

    public DistTodos1Builder cpAlf(String cpAlf) {
        distTodos1.setCpAlf(cpAlf);
        return this;
    }

    public DistTodos1Builder latitude(String latitude) {
        distTodos1.setLatitude(latitude);
        return this;
    }

    public DistTodos1Builder longitude(String longitude) {
        distTodos1.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DistTodos1 build() {
        return distTodos1;
    }
}