/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class DistMultiplos1Builder {
    //the instance to build
    private DistMultiplos1 distMultiplos1;

    /**
     * Default constructor to initialize the instance
     */
    public DistMultiplos1Builder() {
        distMultiplos1 = new DistMultiplos1();
    }

    public DistMultiplos1Builder designacaoDistrito(String designacaoDistrito) {
        distMultiplos1.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DistMultiplos1 build() {
        return distMultiplos1;
    }
}