/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class GeralBuilder {
    //the instance to build
    private Geral geral;

    /**
     * Default constructor to initialize the instance
     */
    public GeralBuilder() {
        geral = new Geral();
    }

    public GeralBuilder id(int id) {
        geral.setId(id);
        return this;
    }

    public GeralBuilder designacaoDistrito(String designacaoDistrito) {
        geral.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public GeralBuilder designacaoConcelho(String designacaoConcelho) {
        geral.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public GeralBuilder codLocalidade(String codLocalidade) {
        geral.setCodLocalidade(codLocalidade);
        return this;
    }

    public GeralBuilder localidade(String localidade) {
        geral.setLocalidade(localidade);
        return this;
    }

    public GeralBuilder artCod(String artCod) {
        geral.setArtCod(artCod);
        return this;
    }

    public GeralBuilder artTipo(String artTipo) {
        geral.setArtTipo(artTipo);
        return this;
    }

    public GeralBuilder priPrep(String priPrep) {
        geral.setPriPrep(priPrep);
        return this;
    }

    public GeralBuilder artTitulo(String artTitulo) {
        geral.setArtTitulo(artTitulo);
        return this;
    }

    public GeralBuilder segPrep(String segPrep) {
        geral.setSegPrep(segPrep);
        return this;
    }

    public GeralBuilder artDesig(String artDesig) {
        geral.setArtDesig(artDesig);
        return this;
    }

    public GeralBuilder artLocal(String artLocal) {
        geral.setArtLocal(artLocal);
        return this;
    }

    public GeralBuilder troco(String troco) {
        geral.setTroco(troco);
        return this;
    }

    public GeralBuilder porta(String porta) {
        geral.setPorta(porta);
        return this;
    }

    public GeralBuilder cliente(String cliente) {
        geral.setCliente(cliente);
        return this;
    }

    public GeralBuilder codPostal4(String codPostal4) {
        geral.setCodPostal4(codPostal4);
        return this;
    }

    public GeralBuilder codPostal3(String codPostal3) {
        geral.setCodPostal3(codPostal3);
        return this;
    }

    public GeralBuilder cpAlf(String cpAlf) {
        geral.setCpAlf(cpAlf);
        return this;
    }

    public GeralBuilder latitude(String latitude) {
        geral.setLatitude(latitude);
        return this;
    }

    public GeralBuilder longitude(String longitude) {
        geral.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Geral build() {
        return geral;
    }
}