/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class MorCodigo7ABuilder {
    //the instance to build
    private MorCodigo7A morCodigo7A;

    /**
     * Default constructor to initialize the instance
     */
    public MorCodigo7ABuilder() {
        morCodigo7A = new MorCodigo7A();
    }

    public MorCodigo7ABuilder id(int id) {
        morCodigo7A.setId(id);
        return this;
    }

    public MorCodigo7ABuilder designacaoDistrito(String designacaoDistrito) {
        morCodigo7A.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public MorCodigo7ABuilder designacaoConcelho(String designacaoConcelho) {
        morCodigo7A.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public MorCodigo7ABuilder codLocalidade(String codLocalidade) {
        morCodigo7A.setCodLocalidade(codLocalidade);
        return this;
    }

    public MorCodigo7ABuilder localidade(String localidade) {
        morCodigo7A.setLocalidade(localidade);
        return this;
    }

    public MorCodigo7ABuilder artCod(String artCod) {
        morCodigo7A.setArtCod(artCod);
        return this;
    }

    public MorCodigo7ABuilder artTipo(String artTipo) {
        morCodigo7A.setArtTipo(artTipo);
        return this;
    }

    public MorCodigo7ABuilder priPrep(String priPrep) {
        morCodigo7A.setPriPrep(priPrep);
        return this;
    }

    public MorCodigo7ABuilder artTitulo(String artTitulo) {
        morCodigo7A.setArtTitulo(artTitulo);
        return this;
    }

    public MorCodigo7ABuilder segPrep(String segPrep) {
        morCodigo7A.setSegPrep(segPrep);
        return this;
    }

    public MorCodigo7ABuilder artDesig(String artDesig) {
        morCodigo7A.setArtDesig(artDesig);
        return this;
    }

    public MorCodigo7ABuilder artLocal(String artLocal) {
        morCodigo7A.setArtLocal(artLocal);
        return this;
    }

    public MorCodigo7ABuilder troco(String troco) {
        morCodigo7A.setTroco(troco);
        return this;
    }

    public MorCodigo7ABuilder porta(String porta) {
        morCodigo7A.setPorta(porta);
        return this;
    }

    public MorCodigo7ABuilder cliente(String cliente) {
        morCodigo7A.setCliente(cliente);
        return this;
    }

    public MorCodigo7ABuilder codPostal4(String codPostal4) {
        morCodigo7A.setCodPostal4(codPostal4);
        return this;
    }

    public MorCodigo7ABuilder codPostal3(String codPostal3) {
        morCodigo7A.setCodPostal3(codPostal3);
        return this;
    }

    public MorCodigo7ABuilder cpAlf(String cpAlf) {
        morCodigo7A.setCpAlf(cpAlf);
        return this;
    }

    public MorCodigo7ABuilder latitude(String latitude) {
        morCodigo7A.setLatitude(latitude);
        return this;
    }

    public MorCodigo7ABuilder longitude(String longitude) {
        morCodigo7A.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MorCodigo7A build() {
        return morCodigo7A;
    }
}