/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class MorCodigo4ABuilder {
    //the instance to build
    private MorCodigo4A morCodigo4A;

    /**
     * Default constructor to initialize the instance
     */
    public MorCodigo4ABuilder() {
        morCodigo4A = new MorCodigo4A();
    }

    public MorCodigo4ABuilder id(int id) {
        morCodigo4A.setId(id);
        return this;
    }

    public MorCodigo4ABuilder designacaoDistrito(String designacaoDistrito) {
        morCodigo4A.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public MorCodigo4ABuilder designacaoConcelho(String designacaoConcelho) {
        morCodigo4A.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public MorCodigo4ABuilder codLocalidade(String codLocalidade) {
        morCodigo4A.setCodLocalidade(codLocalidade);
        return this;
    }

    public MorCodigo4ABuilder localidade(String localidade) {
        morCodigo4A.setLocalidade(localidade);
        return this;
    }

    public MorCodigo4ABuilder artCod(String artCod) {
        morCodigo4A.setArtCod(artCod);
        return this;
    }

    public MorCodigo4ABuilder artTipo(String artTipo) {
        morCodigo4A.setArtTipo(artTipo);
        return this;
    }

    public MorCodigo4ABuilder priPrep(String priPrep) {
        morCodigo4A.setPriPrep(priPrep);
        return this;
    }

    public MorCodigo4ABuilder artTitulo(String artTitulo) {
        morCodigo4A.setArtTitulo(artTitulo);
        return this;
    }

    public MorCodigo4ABuilder segPrep(String segPrep) {
        morCodigo4A.setSegPrep(segPrep);
        return this;
    }

    public MorCodigo4ABuilder artDesig(String artDesig) {
        morCodigo4A.setArtDesig(artDesig);
        return this;
    }

    public MorCodigo4ABuilder artLocal(String artLocal) {
        morCodigo4A.setArtLocal(artLocal);
        return this;
    }

    public MorCodigo4ABuilder troco(String troco) {
        morCodigo4A.setTroco(troco);
        return this;
    }

    public MorCodigo4ABuilder porta(String porta) {
        morCodigo4A.setPorta(porta);
        return this;
    }

    public MorCodigo4ABuilder cliente(String cliente) {
        morCodigo4A.setCliente(cliente);
        return this;
    }

    public MorCodigo4ABuilder codPostal4(String codPostal4) {
        morCodigo4A.setCodPostal4(codPostal4);
        return this;
    }

    public MorCodigo4ABuilder codPostal3(String codPostal3) {
        morCodigo4A.setCodPostal3(codPostal3);
        return this;
    }

    public MorCodigo4ABuilder cpAlf(String cpAlf) {
        morCodigo4A.setCpAlf(cpAlf);
        return this;
    }

    public MorCodigo4ABuilder latitude(String latitude) {
        morCodigo4A.setLatitude(latitude);
        return this;
    }

    public MorCodigo4ABuilder longitude(String longitude) {
        morCodigo4A.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MorCodigo4A build() {
        return morCodigo4A;
    }
}