/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class MorTodas1Builder {
    //the instance to build
    private MorTodas1 morTodas1;

    /**
     * Default constructor to initialize the instance
     */
    public MorTodas1Builder() {
        morTodas1 = new MorTodas1();
    }

    public MorTodas1Builder id(int id) {
        morTodas1.setId(id);
        return this;
    }

    public MorTodas1Builder designacaoDistrito(String designacaoDistrito) {
        morTodas1.setDesignacaoDistrito(designacaoDistrito);
        return this;
    }

    public MorTodas1Builder designacaoConcelho(String designacaoConcelho) {
        morTodas1.setDesignacaoConcelho(designacaoConcelho);
        return this;
    }

    public MorTodas1Builder codLocalidade(String codLocalidade) {
        morTodas1.setCodLocalidade(codLocalidade);
        return this;
    }

    public MorTodas1Builder localidade(String localidade) {
        morTodas1.setLocalidade(localidade);
        return this;
    }

    public MorTodas1Builder artCod(String artCod) {
        morTodas1.setArtCod(artCod);
        return this;
    }

    public MorTodas1Builder artTipo(String artTipo) {
        morTodas1.setArtTipo(artTipo);
        return this;
    }

    public MorTodas1Builder priPrep(String priPrep) {
        morTodas1.setPriPrep(priPrep);
        return this;
    }

    public MorTodas1Builder artTitulo(String artTitulo) {
        morTodas1.setArtTitulo(artTitulo);
        return this;
    }

    public MorTodas1Builder segPrep(String segPrep) {
        morTodas1.setSegPrep(segPrep);
        return this;
    }

    public MorTodas1Builder artDesig(String artDesig) {
        morTodas1.setArtDesig(artDesig);
        return this;
    }

    public MorTodas1Builder artLocal(String artLocal) {
        morTodas1.setArtLocal(artLocal);
        return this;
    }

    public MorTodas1Builder troco(String troco) {
        morTodas1.setTroco(troco);
        return this;
    }

    public MorTodas1Builder porta(String porta) {
        morTodas1.setPorta(porta);
        return this;
    }

    public MorTodas1Builder cliente(String cliente) {
        morTodas1.setCliente(cliente);
        return this;
    }

    public MorTodas1Builder codPostal4(String codPostal4) {
        morTodas1.setCodPostal4(codPostal4);
        return this;
    }

    public MorTodas1Builder codPostal3(String codPostal3) {
        morTodas1.setCodPostal3(codPostal3);
        return this;
    }

    public MorTodas1Builder cpAlf(String cpAlf) {
        morTodas1.setCpAlf(cpAlf);
        return this;
    }

    public MorTodas1Builder latitude(String latitude) {
        morTodas1.setLatitude(latitude);
        return this;
    }

    public MorTodas1Builder longitude(String longitude) {
        morTodas1.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public MorTodas1 build() {
        return morTodas1;
    }
}