/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example;

import com.example.controllers.*;
import com.example.http.client.HttpClient;

public class CodigoPostalPortugalClient {
    /**
     * Singleton access to Distritos controller
     * @return	Returns the DistritosController instance 
     */
    public DistritosController getDistritos() {
        return DistritosController.getInstance();
    }

    /**
     * Singleton access to Concelhos controller
     * @return	Returns the ConcelhosController instance 
     */
    public ConcelhosController getConcelhos() {
        return ConcelhosController.getInstance();
    }

    /**
     * Singleton access to Moradas controller
     * @return	Returns the MoradasController instance 
     */
    public MoradasController getMoradas() {
        return MoradasController.getInstance();
    }

    /**
     * Singleton access to Codigos controller
     * @return	Returns the CodigosController instance 
     */
    public CodigosController getCodigos() {
        return CodigosController.getInstance();
    }

    /**
     * Singleton access to Misc controller
     * @return	Returns the MiscController instance 
     */
    public MiscController getMisc() {
        return MiscController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public CodigoPostalPortugalClient() {
    }

}