/*
 * CodigoPostalPortugalLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.example.models.*;
import com.example.exceptions.*;
import com.example.APIHelper;
import com.example.Configuration;
import com.example.testing.TestHelper;
import com.example.controllers.MiscController;

import com.fasterxml.jackson.core.type.TypeReference;

public class MiscControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static MiscController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getMisc();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Erro. Endpoints válidos: [ distritos | concelhos | moradas | codigos ]
     * @throws Throwable
     */
    @Test
    public void testHomeErro() throws Throwable {

        // Set callback and perform API call
        controller.setHttpCallBack(httpResponse);
        try {
        controller.getHomeErro();
        } catch(HomeErro1Exception e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 404", 
                404, httpResponse.getResponse().getStatusCode());

    }

}
